Accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name="login"),
    path('register', views.registration_form, name="register"),
    path('logout', views.log_out, name="logout"),
    path('username/verify', views.verify_username, name="verify_username"),
    path('email/verify', views.verify_email, name="verify_email"),
    path('preauth', views.pre_authenticate, name="pre_authenticate"),
    path('profile/', views.profile, name="profile"),
    path('profile/image', views.upload_profile_image, name="profile_image"),
    path('password/reset', views.password_reset, name="password_reset"),
]

Info/urls.py
from django.urls import path

from . import views

app_name = "info"

urlpatterns = [
    path('home', views.home, name="home"),
    path('about', views.about, name="about"),
    path('faq', views.faq, name="faq"),
    path('schedule', views.schedule, name="schedule"),
]

ntech/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from Info.views import home

urlpatterns = [
                  path('', home),
                  path('config/', admin.site.urls),
                  path('info/', include('Info.urls', namespace="info")),
                  path('accounts/', include('Accounts.urls', namespace="accounts")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
    {% comment "additional stylesheets for this template go here" %}{% endcomment %}
    <link rel="stylesheet" href={% static "css/home.css" %}>
{% endblock %}
{% block header %}
    <div class="menubar">
        <p class="logo-text menubar left"><img alt="ntech-logo" src={% static "images/favicon.png" %}>tech</p>
        <ul id="menubar" class="menubar left" role="menubar">
            <li class="menuitem"><a href={% url "info:home" %}>Home</a></li>
            <li class="menuitem"><a href={% url "info:schedule" %}>Schedule</a></li>
            <li class="menuitem"><a href={% url "info:faq" %}>FAQ</a></li>
            <li class="menuitem active"><a>About</a></li>
        </ul>
    </div>
    <div id="menu-actions" class="menubar force-right">
        {% if user.is_authenticated %}
            <a class="medium-description blue" href={% url "accounts:profile" %}>
                <img class="thumbnail left" src="{{ user.profile.get_avatar }}">&nbsp;
                {{ user.username }}
            </a>&nbsp;
            <a title="Sign out" class="medium-description round-btn" href={% url "accounts:logout" %}><i
                class="ion-log-out"></i></a>
        {% else %}
            <a class="medium-description blue" href={% url "accounts:login" %}><i class="ion-ios-person"></i>&nbsp;Sign
                in</a>
        {% endif %}
    </div>
    <p id="menu-btn" class="menubar force-right" style="padding: 0 10px 0 10px"><i
            class="ion-android-menu medium-description" style="font-size: 1.5em"></i></p>
{% endblock %}
{% block content %}
    <div class="overlay invisible">
        <!--For responsive menu. Ensure it is present for pages with the responsive menu-->
        <div id="menu-list" class="ruled hidden">
            <ul role="menubar">
                <li class="menuitem-v"><a href={% url "info:home" %}><i class="ion-ios-home"></i>Home</a></li>
                <li class="menuitem-v"><a href={% url "info:schedule" %}><i class="ion-ios-stopwatch blue"></i>Schedule</a>
                </li>
                <li class="menuitem-v"><a href={% url "info:faq" %}><i class="ion-help-circled blue"></i>FAQ</a></li>
                <li class="menuitem-v active"><a><img width="20px" height="20px" alt="ntect-logo"
                                                      src={% static "images/favicon.png" %}>&nbsp;About</a></li>
            </ul>
            <hr style="width: 80%;margin: 20px auto">
            <ul role="menubar">
                <li class="menuitem-v blue"><a href={% url "accounts:register" %}><i class="ion-ios-person"></i>Register</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="menuitem-v blue">
                        <a href={% url "accounts:profile" %}>
                            <img class="user-img" src="{{ user.profile.get_avatar }}">
                            {{ user.username }}
                        </a>
                    </li>
                    <li class="menuitem-v blue"><a href={% url "accounts:logout" %}><i class="ion-log-out"></i>&nbsp;Sign
                        out</a></li>
                {% else %}
                    <li class="menuitem-v blue"><a href={% url "accounts:login" %}><i class="ion-log-in blue"></i>Sign
                        in</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    {% include "under_construction.html" %}
{% endblock %}

templates/faq.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
    {% comment "additional stylesheets for this template go here" %}{% endcomment %}
    <link rel="stylesheet" href={% static "css/home.css" %}>
{% endblock %}
{% block header %}
    <div class="menubar">
        <p class="logo-text menubar left"><img alt="ntech-logo" src={% static "images/favicon.png" %}>tech</p>
        <ul id="menubar" class="menubar left" role="menubar">
            <li class="menuitem"><a href={% url "info:home" %}>Home</a></li>
            <li class="menuitem"><a href={% url "info:schedule" %}>Schedule</a></li>
            <li class="menuitem active"><a>FAQ</a></li>
            <li class="menuitem"><a href={% url "info:about" %}>About</a></li>
        </ul>
    </div>
    <div id="menu-actions" class="menubar force-right">
        {% if user.is_authenticated %}
            <a class="medium-description blue" href={% url "accounts:profile" %}>
                <img class="thumbnail left" src="{{ user.profile.get_avatar }}">&nbsp;
                {{ user.username }}
            </a>&nbsp;
            <a title="Sign out" class="medium-description round-btn" href={% url "accounts:logout" %}><i
                class="ion-log-out"></i></a>
        {% else %}
            <a class="medium-description blue" href={% url "accounts:login" %}><i class="ion-ios-person"></i>&nbsp;Sign
                in</a>
        {% endif %}
    </div>
    <p id="menu-btn" class="menubar force-right" style="padding: 0 10px 0 10px"><i
            class="ion-android-menu medium-description" style="font-size: 1.5em"></i></p>
{% endblock %}
{% block content %}
    <div class="overlay invisible">
        <!--For responsive menu. Ensure it is present for pages with the responsive menu-->
        <div id="menu-list" class="ruled hidden">
            <ul role="menubar">
                <li class="menuitem-v"><a href={% url "info:home" %}><i class="ion-ios-home"></i>Home</a></li>
                <li class="menuitem-v"><a href={% url "info:schedule" %}><i class="ion-ios-stopwatch blue"></i>Schedule</a>
                </li>
                <li class="menuitem-v active"><a><i class="ion-help-circled blue"></i>FAQ</a></li>
                <li class="menuitem-v"><a href={% url "info:about" %}><img width="20px" height="20px" alt="ntect-logo"
                                                                           src={% static "images/favicon.png" %}>&nbsp;About</a>
                </li>
            </ul>
            <hr style="width: 80%;margin: 20px auto">
            <ul role="menubar">
                <li class="menuitem-v blue"><a href={% url "accounts:register" %}><i class="ion-ios-person"></i>Register</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="menuitem-v blue">
                        <a href={% url "accounts:profile" %}>
                            <img class="user-img" src="{{ user.profile.get_avatar }}">
                            {{ user.username }}
                        </a>
                    </li>
                    <li class="menuitem-v blue"><a href={% url "accounts:logout" %}><i class="ion-log-out"></i>&nbsp;Sign
                        out</a></li>
                {% else %}
                    <li class="menuitem-v blue"><a href={% url "accounts:login" %}><i class="ion-log-in blue"></i>Sign
                        in</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    {% include "under_construction.html" %}
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
    {% comment "additional stylesheets for this template go here" %}{% endcomment %}
    <link rel="stylesheet" href={% static "css/home.css" %}>
{% endblock %}
{% block header %}
    <div class="menubar">
        <p class="logo-text menubar left"><img alt="ntech-logo" src={% static "images/favicon.png" %}>tech</p>
        <ul id="menubar" class="menubar left" role="menubar">
            <li class="menuitem active"><a>Home</a></li>
            <li class="menuitem"><a href={% url "info:schedule" %}>Schedule</a></li>
            <li class="menuitem"><a href={% url "info:faq" %}>FAQ</a></li>
            <li class="menuitem"><a href={% url "info:about" %}>About</a></li>
        </ul>
    </div>
    <div id="menu-actions" class="menubar force-right">
        {% if user.is_authenticated %}
            <a class="medium-description blue" href={% url "accounts:profile" %}>
                <img class="thumbnail left" src="{{ user.profile.get_avatar }}">&nbsp;
                {{ user.username }}
            </a>&nbsp;
            <a title="Sign out" class="medium-description round-btn" href={% url "accounts:logout" %}><i
                class="ion-log-out"></i></a>
        {% else %}
            <a class="medium-description blue" href={% url "accounts:login" %}><i class="ion-ios-person"></i>&nbsp;Sign
                in</a>
        {% endif %}
    </div>
    <p id="menu-btn" class="menubar force-right" style="padding: 0 10px 0 10px"><i
            class="ion-android-menu medium-description" style="font-size: 1.5em"></i></p>
{% endblock %}
{% block content %}
    <div class="overlay invisible">
        <!--For responsive menu. Ensure it is present for pages with the responsive menu-->
        <div id="menu-list" class="ruled hidden">
            <ul role="menubar">
                <li class="menuitem-v active"><a><i class="ion-ios-home"></i>Home</a></li>
                <li class="menuitem-v"><a href={% url "info:schedule" %}><i class="ion-ios-stopwatch blue"></i>Schedule</a>
                </li>
                <li class="menuitem-v"><a href={% url "info:faq" %}><i class="ion-help-circled blue"></i>FAQ</a></li>
                <li class="menuitem-v"><a href={% url "info:about" %}><img width="20px" height="20px" alt="ntect-logo"
                                                        src={% static "images/favicon.png" %}>&nbsp;About</a></li>
            </ul>
            <hr style="width: 80%;margin: 20px auto">
            <ul role="menubar">
                <li class="menuitem-v blue"><a href={% url "accounts:register" %}><i class="ion-ios-person"></i>Register</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="menuitem-v blue">
                        <a href={% url "accounts:profile" %}>
                            <img class="user-img" src="{{ user.profile.get_avatar }}">
                            {{ user.username }}
                        </a>
                    </li>
                    <li class="menuitem-v blue"><a href={% url "accounts:logout" %}><i class="ion-log-out"></i>&nbsp;Sign
                        out</a></li>
                {% else %}
                    <li class="menuitem-v blue"><a href={% url "accounts:login" %}><i class="ion-log-in blue"></i>Sign
                        in</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div id="main-desc" class="container medium-description waypoint">
        <img id="logo-img" class="left img" src={% static "images/ntech.png" %}>
        <div id="main-desc-text" class="medium-description">
            <p class="large-description container">Ntech Hackathon 2019</p>
            <strong>N-Tech</strong> (<i>New Technologists & Innovators</i>) is a youth-led initiative that aims to
            empower youth to drive technological advancements as the fourth Industrial Revolution unveils. Young
            people today are going to be the leaders of tomorrow. But, is it not mismatching that one third of the,
            rapidly accelerating, youth population in Africa is unemployed today?<br>
            N-Tech hackathon is an annual event and we are currently seeking
            Participants (undergraduate or graduate university students) and sponsors for this year's event. They will
            team-up
            depending on topics that they are mutually interested in, work together for 30 hours to develop a solution
            to the prompt. Thereafter, submissions will be evaluated by a panel of judges and the selected finalists
            will pitch their ideas to the organizations. Top teams will then be selected.
        </div>
    </div>
    <div class="container ruled waypoint" style="height: 40px; margin-top: 20px;padding-bottom: 20px">
        <a href={% url "accounts:register" %}>
            <button class="blue-btn center" style="width: 120px;">Register</button>
        </a>
        <a href={% url "info:about" %}>
            <button class="blue-btn center" style="width: 120px;">Read more</button>
        </a>
    </div>
    <p class="large-description blue waypoint">Currently involving three countries</p>
    <p class="container blockquote waypoint-side" style="max-width: 800px">
        This year, 2019, it will concurrently be hosted in Kenya, Rwanda, and Uganda (we hope to expand in the future).
        Each country will have a theme
        that relates to some of the major issues but still contributes to our overall mission, empowering youth to
        take the lead in the fourth industrial revolution.
    </p>
    <div class="container">
        <img id="map-img" class="wide-img center waypoint" alt="countries-kenya-uganda-rwanda"
             src={% static "images/map.png" %}>
    </div>
    <div id="commentaries" class="ruled">
        <div class="commentary waypoint-side" style="background: rgba(225, 77, 17, 0.28)">
            <img class="comm-prof-img" src={% static "images/rwanda.jpg" %}>
            <p class="small-description comm-text">
                Ntech hackathon is a novel way of bringing young people to put their heads together for the
                realisation of goals that will propel Africa to greater heights. We at Rwanda are proud to be part of
                this groundbreaking initiative.
            </p>
            <p class="commentor right">~ Resire, Rwanda</p>
        </div>
        <div class="commentary waypoint-side" style="background: rgba(113, 197, 241, 0.24)">
            <img class="comm-prof-img" src={% static "images/uganda.jpg" %}>
            <p class="small-description comm-text">
                When I first heard of this innovative endeavour I knew that I would not let this slip away. I have
                always wondered how I would lend a hand in making Uganda and continent great and alas! This is it,
                the Ntech hackathon. A chance for me to breathe life into ideas that will move Africa.
            </p>
            <p class="commentor right">~ Silas, Uganda</p>
        </div>
        <div class="commentary waypoint-side terminate" style="background: rgba(171, 141, 193, 0.28);">
            <img class="comm-prof-img" src={% static "images/kenya.jpg" %}>
            <p class="small-description comm-text">
                Technology in Africa is like a sprouting seedling which I among others, through the Ntech hackathon,
                intend to tend to till it's a massive tree. A massive tree under which future generations can enjoy a
                soothing shade. Generations not just from Kenya or this continent but from the entire globe.
            </p>
            <p class="commentor right">~ Ronald, Kenya</p>
        </div>
    </div>
    <p class="large-description container waypoint" id="social-intro" style="margin-top: 40px;">Know more about us</p>
    <p class="small-description container waypoint" style=";max-width: 600px; margin: 0 auto">Follow, Add and and friend
        us on all popular platforms
        and get to experience the great things we do. Find our groundbreaking creations on github. We really hope you
        can
        add to our vast collection.</p>
    <div class="container" id="social">
        <div class="social-link waypoint-side">
            <a href="#">
                <i class="ion-social-instagram"></i>
                <span>Instagram</span>
            </a>
        </div>
        <div class="social-link waypoint-side">
            <i class="ion-social-facebook"></i>
            <span>Facebook</span>
        </div>
        <div class="social-link waypoint-side">
            <i class="ion-social-twitter"></i>
            <span>Twitter</span>
        </div>
        <div class="social-link waypoint-side terminate">
            <i class="ion-social-github"></i>
            <span>Github</span>
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
    {% comment "additional stylesheets for this template go here" %}{% endcomment %}
    <link rel="stylesheet" href={% static "css/forms.css" %}>
{% endblock %}
{% block header %}
    <div class="menubar">
        <p class="logo-text menubar left"><img alt="ntech-logo" src={% static "images/favicon.png" %}>tech</p>
        <ul id="menubar" class="menubar left" role="menubar">
            <li class="menuitem"><a href={% url "info:home" %}>Home</a></li>
            <li class="menuitem"><a href={% url "info:schedule" %}>Schedule</a></li>
            <li class="menuitem"><a href={% url "info:faq" %}>FAQ</a></li>
            <li class="menuitem"><a href={% url "info:about" %}>About</a></li>
        </ul>
    </div>
    <div id="menu-actions" class="menubar force-right">
        {% if user.is_authenticated %}
            <a class="medium-description blue"><i class="ion-ios-person"></i>&nbsp;{{ user.username }}</a>&nbsp;
            <a title="Sign out" class="medium-description round-btn" href={% url "accounts:logout" %}><i
                    class="ion-log-out"></i></a>
        {% endif %}
    </div>
    <p id="menu-btn" class="menubar force-right" style="padding: 0 10px 0 10px"><i
            class="ion-android-menu medium-description" style="font-size: 1.5em"></i></p>

{% endblock %}
{% block content %}
    <div class="overlay invisible">
        <!--For responsive menu. Ensure it is present for pages with the responsive menu-->
        <div id="menu-list" class="ruled hidden">
            <ul role="menubar">
                <li class="menuitem-v"><a href={% url "info:home" %}><i class="ion-ios-home"></i>Home</a></li>
                <li class="menuitem-v"><a href={% url "info:schedule" %}><i class="ion-ios-stopwatch blue"></i>Schedule</a>
                </li>
                <li class="menuitem-v"><a href={% url "info:faq" %}><i class="ion-help-circled blue"></i>FAQ</a></li>
                <li class="menuitem-v"><a href={% url "info:about" %}><img width="20px" height="20px" alt="ntect-logo"
                                                        src={% static "images/favicon.png" %}>&nbsp;About</a></li>
            </ul>
            <hr style="width: 80%;margin: 20px auto">
            <ul role="menubar">
                <li class="menuitem-v blue"><a href={% url "accounts:register" %}><i class="ion-ios-person"></i>Register</a>
                </li>
            </ul>
        </div>
    </div>
    <form method="post" autocomplete="off" id="login-form">
        <!--img alt="ntech" class="sign-in-logo waypoint" src={% static "images/ntech.png" %}-->
        <p class=" container medium-description waypoint blue">Access Your Account</p>
        {% csrf_token %}
        <div class="input-layer waypoint-side">
            <span class="placeholder"><i class="ion-ios-person"></i>&nbsp;&nbsp;Username</span>
            <input id="id_username" type="text" name="username" class="data">
            <div class="flash"></div>
            <div class="flash-inactive"></div>
            <p class="error" id="lun-err"></p>
        </div>
        <div class="input-layer waypoint-side">
            <span class="placeholder"><i class="ion-ios-locked"></i>&nbsp;&nbsp;Password</span>
            <input id="id_password" type="password" name="password" class="data">
            <div class="flash"></div>
            <div class="flash-inactive"></div>
            <p class="error" id="lpw-err"></p>
        </div>

        <p class="container small-description waypoint limit-width" style="display: block; margin-top: 20px">
            You do not have an account?&nbsp;<a class="blue" href={% url "accounts:register" %}>Sign up</a>
            &nbsp;today to be a part of us.
        </p>

        <div class="container" style="margin:60px 0 60px 0">
            <input id="sign_in" type="submit" hidden>
            <input type="button" class="blue-btn" value="Sign in" id="pre-submit">
        </div>
    </form>
{% endblock %}
{% block scripts %}
    <script src={% static "js/validators.js" %}></script>
{% endblock %}

templates/schedule.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
    {% comment "additional stylesheets for this template go here" %}{% endcomment %}
    <link rel="stylesheet" href={% static "css/home.css" %}>
    <link rel="stylesheet" href={% static "css/forms.css" %}>
    <style>
        #schedule-body {
            width: 98%;
            margin: 1%;
            height: 96%;
        }

        .schedule-nav {
            height: 7%;
            width: 100%;
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        #schedule-content {
            height: 84%;
            width: 100%;
            overflow: auto;
        }

        .schedule-controls, #schedule-current {
            height: auto;
            display: inline-flex;
            align-items: center;
        }

        .schedule-controls {
            float: right;
            width: fit-content;
            max-width: 300px;
        }

        .schedule-controls .select-val {
            height: 30px;
        }

        .search-input {
            width: 40%;
            max-width: 250px;
            padding: 0 10px 0 10px;
            border: solid 1px var(--universal-text-color);
            border-radius: 8px;
            font-family: Calibri, sans-serif;
            color: var(--lively-text-color);
            background: inherit;
            height: 30px;
            font-size: 110%;
            display: inline-block;
        }

        .inline-select-layer {
            position: relative;
            display: inline-block !important;
            margin: 0 10px 0 10px;
            height: 32px;
        }

        .content {
            overflow: hidden !important;
        }

        #schedule-current {
            padding: 5px 0 0 0;
            margin-left: 2%;
            justify-content: left;
            font-family: Calibri, sans-serif;
            color: var(--universal-text-color);
        }

        .event-collection {
            width: 96%;
            max-width: 900px;
            margin: 15px auto;
            box-shadow: 0 0 2px 2px #ccc;
            border-radius: 5px;
            height: fit-content;
            transition: all 1s var(--easing);
            overflow: hidden;
            animation: fadein 0.4s ease-in;
            position: relative;
        }

        .event-control, .event-item-title {
            height: 40px;
            display: flex;
            align-items: center;
            border-bottom: solid 1px #ccd8ff;
            font-family: Calibri, sans-serif;
            justify-content: space-between;
        }

        .event-item {
            width: 96%;
            margin: 30px auto;
            position: relative;
            height: fit-content;
        }

        .event-item-title {
            position: relative;
            background: rgba(113, 197, 241, 0.24);
            height: 30px;
        }

        .duration {
            position: absolute;
            top: 29px;
            height: 70%;
            align-items: center;
            display: inline-block;
            left: 0;
            width: 10%;
            font-size: 90%;
            font-family: Calibri, sans-serif;
            overflow: hidden;
        }

        .duration span {
            background: var(--bright-text-color);
            z-index: 2;
            width: 100%;
            display: flex;
            justify-content: center;
        }

        .duration-strip {
            height: 90%;
            background: var(--lively-text-color);
            width: 2px;
            position: absolute;
            left: 7%;
            top: 50px;
        }

        .force-bottom {
            position: absolute;
            bottom: 0;
        }

        .event-item-title .round-btn-2 {
            height: 25px;
            width: 25px;
            border-radius: 13px;
            background: transparent;
        }

        .event-item-title .round-btn-2:hover {
            box-shadow: inset 0 0 0 13px var(--lively-text-color);
        }

        .event-item-holder {
            margin-bottom: 10px;
        }

        .event-item-body {
            font-family: "Segoe UI", sans-serif;
            padding: 10px 0 10px 0;
        }

        .event-item-body, .event-item-title {
            width: 90%;
            left: 10%;
            position: relative;
        }

        .event-collapsed {
            height: 40px !important;
        }

        @media screen and (max-width: 560px) {
            .event-item-title, .event-item-body {
                width: 80%;
                font-size: 90%;
                left: 20%;
            }

            .duration {
                width: 20%;
            }

            .duration-strip {
                left: 11%;
            }

            .schedule-controls .round-btn-2 {
                width: 25px;
                height: 25px;
                border-radius: 13px;
                font-size: 15px;
                margin: 1px;
            }

            #schedule-current {
                font-size: 80%;
            }
        }
    </style>
{% endblock %}
{% block header %}
    <div class="menubar">
        <p class="logo-text menubar left"><img alt="ntech-logo" src={% static "images/favicon.png" %}>tech</p>
        <ul id="menubar" class="menubar left" role="menubar">
            <li class="menuitem"><a href={% url "info:home" %}>Home</a></li>
            <li class="menuitem active"><a href={% url "info:schedule" %}>Schedule</a></li>
            <li class="menuitem"><a href={% url "info:faq" %}>FAQ</a></li>
            <li class="menuitem"><a href={% url "info:about" %}>About</a></li>
        </ul>
    </div>
    <div id="menu-actions" class="menubar force-right">
        {% if user.is_authenticated %}
            <a class="medium-description blue" href={% url "accounts:profile" %}>
                <img class="thumbnail left" src="{{ user.profile.get_avatar }}">&nbsp;
                {{ user.username }}
            </a>&nbsp;
            <a title="Sign out" class="medium-description round-btn" href={% url "accounts:logout" %}><i
                class="ion-log-out"></i></a>
        {% else %}
            <a class="medium-description blue" href={% url "accounts:login" %}><i class="ion-ios-person"></i>&nbsp;Sign
                in</a>
        {% endif %}
    </div>
    <p id="menu-btn" class="menubar force-right" style="padding: 0 10px 0 10px"><i
            class="ion-android-menu medium-description" style="font-size: 1.5em"></i></p>
{% endblock %}
{% block content %}
    {% if user.is_staff %}
        {% include "event_creator.html" %}
    {% endif %}
    <div class="overlay invisible">
        <!--For responsive menu. Ensure it is present for pages with the responsive menu-->
        <div id="menu-list" class="ruled hidden">
            <ul role="menubar">
                <li class="menuitem-v"><a href={% url "info:home" %}><i class="ion-ios-home"></i>Home</a></li>
                <li class="menuitem-v active"><a href={% url "info:schedule" %}><i class="ion-ios-stopwatch blue"></i>Schedule</a>
                </li>
                <li class="menuitem-v"><a href={% url "info:faq" %}><i class="ion-help-circled blue"></i>FAQ</a></li>
                <li class="menuitem-v"><a href={% url "info:about" %}><img width="20px" height="20px" alt="ntect-logo"
                                                                           src={% static "images/favicon.png" %}>&nbsp;About</a>
                </li>
            </ul>
            <hr style="width: 80%;margin: 20px auto">
            <ul role="menubar">
                <li class="menuitem-v blue"><a href={% url "accounts:register" %}><i class="ion-ios-person"></i>Register</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="menuitem-v blue">
                        <a href={% url "accounts:profile" %}>
                            <img class="user-img" src="{{ user.profile.get_avatar }}">
                            {{ user.username }}
                        </a>
                    </li>
                    <li class="menuitem-v blue"><a href={% url "accounts:logout" %}><i class="ion-log-out"></i>&nbsp;Sign
                        out</a></li>
                {% else %}
                    <li class="menuitem-v blue"><a href={% url "accounts:login" %}><i class="ion-log-in blue"></i>Sign
                        in</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div id="schedule-body">
        <div class="schedule-nav">
            <div id="schedule-current">
                <i class="ion-ios-calendar blue" style="margin-left: 5px"></i>&nbsp;
                <span></span>
            </div>
            <input type="search" class="search-input" id="search" placeholder="Search">
            <div class="schedule-controls">
                <i id="refresh" class="ion-android-refresh round-btn-2 slight-margin" title="refresh"></i>
                <i id="expand" class="ion-chevron-down round-btn-2 slight-margin" title="expand all"></i>
                <i id="collapse" class="ion-chevron-up round-btn-2 slight-margin" title="collapse all"></i>
            </div>
        </div>
        <div id="schedule-content">
            {% if user.is_staff %}
                <i class="round-btn floating-btn ion-ios-plus-empty" id="add-event-btn"></i>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        shadow_on_scroll($(".schedule-nav"), $("#schedule-content"));
        const csrf = '{{ csrf_token }}';
        const s_auth = '{{ user.is_staff }}'
    </script>
    <script src={% static "js/schedule.js" %}></script>
{% endblock %}